server:
  port: 8443
  ssl:
    key-store: file:///path/to/mykeys.jks
    key-store-password: password
    key-password: password

logging:
  level:
  root: WARN
  org:
  springframework:
  security: DEBUG